export const GET_REPO_DATA = "GET_REPO_DATA";
export const GET_REPO_DATA_SUCCESS = "GET_REPO_DATA_SUCCESS";
export const GET_REPO_DATA_FAILED= "GET_REPO_DATA_FAILED";
export const GET_PROFILE_DATA = "GET_PROFILE_DATA";
export const GET_PROFILE_DATA_SUCCESS = "GET_PROFILE_DATA_SUCCESS";
export const GET_PROFILE_DATA_FAILED= "GET_PROFILE_DATA_FAILED";
